patient_tracking/urls.py
from django.urls import path
app_name = 'patient_tracking'

from . import views
urlpatterns=[
    path('', views.dashboard, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('medical-histories/', views.MedicalHistoryListView.as_view(), name='medical-histories-list'),
    path('medical-histories/create/', views.MedicalHistoryCreateView.as_view(), name='medical-histories-create'),
    path('medical-histories/<pk>/', views.MedicalHistoryDetailView.as_view(), name='medical-histories-detail'),
    path('medical-histories/<pk>/edit', views.MedicalHistoryUpdateView.as_view(), name='medical-histories-edit'),

    path('patients/', views.PatientListView.as_view(), name='patients-list'),
    path('patients/create/', views.PatientCreateView.as_view(), name='patients-create'),
    path('patients/<pk>/', views.PatientDetailView.as_view(), name='patients-detail'),
    path('patients/<pk>/edit/', views.PatientUpdateView.as_view(), name='patients-edit'),
]

patient_tracking_system/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("website.urls")),
    path('admin/', admin.site.urls),
    path('patient-tracking/', include('patient_tracking.urls')),
]

website/urls.py
from django.urls import path

from . import views
app_name = 'website'

urlpatterns = [
    path("", views.home, name="home"),
]

patient_tracking/models.py
from django.db import models
from django.utils import timezone
# from django.contrib.auth.models import AbstractUser
from django.shortcuts import render
from django.urls import reverse
# Create your models here.

class Patient(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField()
    gender = models.CharField(max_length=10, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')])
    address = models.TextField()
    phone_number = models.CharField(max_length=20)
    email = models.EmailField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    def get_absolute_url(self):
            return reverse('patient_tracking:patients-detail', args=[self.pk])

class Appointment(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    appointment_date = models.DateTimeField()
    notes = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"Appointment for {self.patient} on {self.appointment_date}"

class MedicalHistory(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    condition = models.CharField(max_length=100)
    diagnosis_date = models.DateField()
    description = models.TextField()

    def __str__(self):
        return f"Medical history of {self.patient} - {self.condition}"
    def get_absolute_url(self):
            return reverse('patient_tracking:medical-histories-detail', args=[self.pk])

class Prescription(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor = models.CharField(max_length=100)
    prescription_date = models.DateField(default=timezone.now)
    medication = models.TextField()
    dosage = models.CharField(max_length=50)
    instructions = models.TextField()

    def __str__(self):
        return f"Prescription for {self.patient.first_name} {self.patient.last_name}"


class Billing(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    bill_date = models.DateField(default=timezone.now)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    payment_status = models.CharField(max_length=20, choices=(
        ('pending', 'Pending'),
        ('paid', 'Paid'),
        ('partially_paid', 'Partially Paid'),
        ('cancelled', 'Cancelled'),
    ))

    def __str__(self):
        return f"Billing for {self.patient.first_name} {self.patient.last_name}"


# class UserAccount(AbstractUser):
#     ROLES = (
#         ('doctor', 'Doctor'),
#         ('nurse', 'Nurse'),
#         ('admin', 'Administrator'),
#         # Add more roles as needed
#     )
#     role = models.CharField(max_length=20, choices=ROLES)

#     def __str__(self):
#         return f"{self.username} ({self.get_role_display()})"
    
#     class Meta:
#         # Add the following line to set a related_name for user_permissions
#         permissions = [
#             ("can_view_patients", "Can view patients"),
#             ("can_manage_appointments", "Can manage appointments"),
#             # Define more permissions as needed
#         ]

website/models.py
from django.db import models

patient_tracking/views.py
from .models import *
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.edit import  FormView, CreateView, UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

# Create your views here.

def dashboard(request): 
    data = {
        'patients': Patient.objects.all(),
        'appointments': Appointment.objects.all(),
        'medical_histories': MedicalHistory.objects.all(),
        'prescriptions': Prescription.objects.all()
    }
    return render(request, 'patient_tracking/dashboard.html', data)

class PatientListView(ListView): 
    model = Patient 
    paginate_by = 100  # if pagination is desired
    template_name = 'patient_tracking/patients/patient_list.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

class PatientCreateView(CreateView): 
    model = Patient 
    fields = '__all__'
    template_name = 'patient_tracking/patients/patient_form.html'

class PatientDetailView(DetailView):
    model = Patient
    template_name = 'patient_tracking/patients/patient_detail.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context
class PatientUpdateView(UpdateView): 
    model = Patient 
    fields = '__all__'
    template_name = 'patient_tracking/patients/patient_form.html'

class MedicalHistoryListView(ListView): 
    model = MedicalHistory 
    paginate_by = 100  # if pagination is desired
    template_name = 'patient_tracking/medical_histories/medical_history_list.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context
class MedicalHistoryCreateView(CreateView): 
    model = MedicalHistory 
    fields = '__all__'
    template_name = 'patient_tracking/medical_histories/medical_history_form.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context
    
class MedicalHistoryDetailView(DetailView):
    model = MedicalHistory
    template_name = 'patient_tracking/medical_histories/medical_history_detail.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context
    
class MedicalHistoryUpdateView(UpdateView): 
    model = MedicalHistory 
    fields = '__all__'
    template_name = 'patient_tracking/medical_histories/medical_history_form.html'

website/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

# Website home page
def home(request):
    # return HttpResponse("Hello, world. You're at our website home page.")
    return render(request, "website/index.html")

patient_tracking/templates/patient_tracking/dashboard.html
{% extends 'website/base.html' %}
{% load static %}
{% block title %}
    Patient Tracking | APP
{% endblock %}
{% block css %}
<style>

.circle-tile {
    margin-bottom: 15px;
    text-align: center;
}
.circle-tile-heading {
    border: 3px solid rgba(255, 255, 255, 0.3);
    border-radius: 100%;
    color: #FFFFFF;
    height: 80px;
    margin: 0 auto -40px;
    position: relative;
    transition: all 0.3s ease-in-out 0s;
    width: 80px;
}
.circle-tile-heading .fa {
    line-height: 80px;
}
.circle-tile-content {
    padding-top: 50px;
}
.circle-tile-number {
    font-size: 26px;
    font-weight: 700;
    line-height: 1;
    padding: 5px 0 15px;
}
.circle-tile-description {
    text-transform: uppercase;
}
.circle-tile-footer {
    background-color: rgba(0, 0, 0, 0.1);
    color: rgba(255, 255, 255, 0.5);
    display: block;
    padding: 5px;
    transition: all 0.3s ease-in-out 0s;
}
.circle-tile-footer:hover {
    background-color: rgba(0, 0, 0, 0.2);
    color: rgba(255, 255, 255, 0.5);
    text-decoration: none;
}
.circle-tile-heading.dark-blue:hover {
    background-color: #2E4154;
}
.circle-tile-heading.green:hover {
    background-color: #138F77;
}
.circle-tile-heading.orange:hover {
    background-color: #DA8C10;
}
.circle-tile-heading.blue:hover {
    background-color: #2473A6;
}
.circle-tile-heading.red:hover {
    background-color: #CF4435;
}
.circle-tile-heading.purple:hover {
    background-color: #7F3D9B;
}
.tile-img {
    text-shadow: 2px 2px 3px rgba(0, 0, 0, 0.9);
}

.dark-blue {
    background-color: #34495E;
}
.green {
    background-color: #16A085;
}
.blue {
    background-color: #2980B9;
}
.orange {
    background-color: #F39C12;
}
.red {
    background-color: #E74C3C;
}
.purple {
    background-color: #8E44AD;
}
.dark-gray {
    background-color: #7F8C8D;
}
.gray {
    background-color: #95A5A6;
}
.light-gray {
    background-color: #BDC3C7;
}
.yellow {
    background-color: #F1C40F;
}
.text-dark-blue {
    color: #34495E;
}
.text-green {
    color: #16A085;
}
.text-blue {
    color: #2980B9;
}
.text-orange {
    color: #F39C12;
}
.text-red {
    color: #E74C3C;
}
.text-purple {
    color: #8E44AD;
}
.text-faded {
    color: rgba(255, 255, 255, 0.7);
}


</style>
{% endblock %}
{% block content %}

<section style="padding-left: 70px; padding-right: 70px;" class="shadow">
    <div class="container bootstrap snippet">
        <div class="row">
          <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="circle-tile ">
              <a href="#"><div class="circle-tile-heading blue"><i class="fa fa-users fa-fw fa-3x"></i></div></a>
              <div class="circle-tile-content blue">
                <div class="circle-tile-description text-faded"> Patients</div>
                <div class="circle-tile-number text-faded ">{{patients.count}}</div>
                <a class="circle-tile-footer" href="{% url 'patient_tracking:patients-list' %}">More Info<i class="fa fa-chevron-circle-right"></i></a>
              </div>
            </div>
          </div>
           
          <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="circle-tile ">
              <a href="#"><div class="circle-tile-heading orange"><i class="fa fa-list fa-fw fa-3x"></i></div></a>
              <div class="circle-tile-content orange">
                <div class="circle-tile-description text-faded"> Appointments </div>
                <div class="circle-tile-number text-faded ">{{appointments.count}}</div>
                <a class="circle-tile-footer" href="#">More Info<i class="fa fa-chevron-circle-right"></i></a>
              </div>
            </div>
          </div> 

          <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="circle-tile ">
              <a href="#"><div class="circle-tile-heading purple"><i class="fa fa-hospital-o fa-fw fa-3x"></i></div></a>
              <div class="circle-tile-content purple">
                <div class="circle-tile-description text-faded"> Medical Histories </div>
                <div class="circle-tile-number text-faded ">{{medical_histories.count}}</div>
                <a class="circle-tile-footer" href="{% url 'patient_tracking:medical-histories-list' %}">More Info<i class="fa fa-chevron-circle-right"></i></a>
              </div>
            </div>
          </div> 
          <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="circle-tile ">
              <a href="#"><div class="circle-tile-heading dark-gray"><i class="fa fa-bookmark fa-fw fa-3x"></i></div></a>
              <div class="circle-tile-content dark-gray">
                <div class="circle-tile-description text-faded"> Prescription </div>
                <div class="circle-tile-number text-faded ">{{prescriptions.count}}</div>
                <a class="circle-tile-footer" href="#">More Info<i class="fa fa-chevron-circle-right"></i></a>
              </div>
            </div>
          </div> 
        </div> 
    </div> 
    <div class="jumbotron">
        <div class="container">
            <h1>PATIENT TRACKING SYSTEM</h1>
            <p>A web application designed to help healthcare facilities, such as hospitals or clinics, efficiently manage and monitor the movement and status of patients within their care. Here's a short description of such an app:</p>
        </div>
    </div>
    <h2>Key Features:</h2>
    <ol>
        <li>Patient Registration: Easily register new patients with essential information.</li>
        <li>Admission and Discharge Management: Track admission and discharge details.</li>
        <li>Real-time Location Tracking: Monitor patient location within the facility.</li>
        <li>Appointment Scheduling: Schedule and manage patient appointments.</li>
        <li>Patient History and Medical Records: Securely store and organize medical records.</li>
        <li>Alerts and Notifications: Receive alerts for critical events.</li>
        <li>Billing and Insurance Integration: Streamline financial aspects of patient care.</li>
        <li>User Access Control: Implement role-based access control.</li>
        <li>Reporting and Analytics: Generate reports and analytics for data-driven decisions.</li>
        <li>Mobile Accessibility: Access patient information on-the-go.</li>
    </ol>

    <h2>Benefits:</h2>
    <ol>
        <li>Improved Patient Care: Enhance patient care quality and coordination.</li>
        <li>Efficient Resource Management: Optimize resource allocation.</li>
        <li>Enhanced Communication: Improve staff communication.</li>
        <li>Data Security: Ensure patient data confidentiality.</li>
        <li>Streamlined Administrative Tasks: Automate administrative processes.</li>
    </ol>

    <p>A Patient Tracking System in Django can significantly benefit healthcare facilities by improving patient care, reducing administrative burdens, and enhancing overall operational efficiency.</p>
</section>

{% endblock %}

patient_tracking/templates/patient_tracking/medical_histories/medical_history_form.html
{% extends 'website/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
    Patient Tracking | Medical Histories Form
{% endblock %}

{% block content %}

<section style="padding: 70px;" class="shadow">
    <div class="container">
        <div class="row my-row">
            <div class="col-sm-6 col-md-3 hidden-xs hidden-sm">
                <img src="{% static 'website/images/blog_1.jpg' %}" class="img-responsive" alt="">
            </div>
            <div class="col-sm-12 col-md-9">
                <div class="about-des">
                    <h3 class="bordered bordered-2 border-bottom bordered-primary">
                        Medical Record 
                        {% if request.path == '/patient-tracking/medical-histories/create/' %}  
                            Registration 
                        {% else %} 
                            Edit 
                        {% endif %} 
                        Form
                    </h3>
                    <h5>
                        {% if request.path == '/patient-tracking/medical-histories/create/' %} 
                            Register a new medical records
                        {% else %} 
                            Update a medical records
                        {% endif %}
                    <a href="{% url 'patient_tracking:medical-histories-list' %}" type="button" class="thm-btn">Medical Histories List</a></h5>
                    
                    {% if form.errors %}
                        <div class="alert alert-danger alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                            <strong>Whoops!</strong> Something went wrong
                            <div class="">
                                {{form.non_field_errors}}
                            </div>    
                      </div>
                    {% endif %}
                     <form method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group {% if form.patient.errors %} has-error {% endif %}">
                                    <label class="control-label" for="{{ form.patient.id_for_label }}">{{ form.patient.label_tag }}</label>
                                    {{ form.patient|append_attr:"class:form-control" }}
                                    <span class="help-block">
                                        {% for error in form.patient.errors %}
                                            {{ error }}
                                        {% endfor %}
                                    </span>
                                  </div>
                            </div>                 
                            <div class="col-md-6">
                                <div class="form-group {% if form.condition.errors%} has-error {% endif %}">
                                    <label class="control-label" for="{{ form.condition.id_for_label }}">{{ form.condition.label_tag }}</label>
                                    {{ form.condition|append_attr:"class:form-control" }}
                                    <span class="help-block">
                                        {% for error in form.condition.errors %}
                                            {{ error }}
                                        {% endfor %}
                                    </span>
                                  </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group {% if form.diagnosis_date.errors %} has-error {% endif %}">
                                    <label class="control-label" for="{{ form.diagnosis_date.id_for_label }}">{{ form.diagnosis_date.label_tag }}</label>
                                    {{ form.diagnosis_date|append_attr:"class:form-control"|attr:"type:date" }}
                                    <span class="help-block">
                                        {% for error in form.diagnosis_date.errors %}
                                            {{ error }}
                                        {% endfor %}
                                    </span>
                                  </div>
                            </div>                 
                            <div class="col-md-12">
                                <div class="form-group {% if form.description.errors%} has-error {% endif %}">
                                    <label class="control-label" for="{{ form.description.id_for_label }}">{{ form.description.label_tag }}</label>
                                    {{ form.description|append_attr:"class:form-control"|attr:"rows:3" }}
                                    <span class="help-block">
                                        {% for error in form.description.errors %}
                                            {{ error }}
                                        {% endfor %}
                                    </span>
                                  </div>
                            </div>

                            <div class="col-lg-12">
                                <div class="btn-toolbar" role="toolbar" aria-label="...">
                                    <div class="btn-group" role="group" aria-label="...">
                                        <button type="reset" class="default-btn btn btn-warning send_btn">Clear<span></span></button>
                                    </div>
                                    <div class="btn-group" role="group" aria-label="...">
                                        <button type="submit" class="default-btn btn btn-primary send_btn">Save<span></span></button>
                                    </div>
                                  </div>
                                <div class="form-group">
                                </div>
                            </div>                     
                        </div>
                     </form>               
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

patient_tracking/templates/patient_tracking/medical_histories/medical_history_list.html
{% extends 'website/base.html' %}
{% load static %}
{% block title %}
    Patient Tracking | Patients
{% endblock %}

{% block content %}

<section style="padding: 70px;" class="shadow">
    <div class="container">
        <div class="row my-row">
            <div class="col-12">
                <div class="about-des">
                    <h3 class="bordered bordered-2 border-bottom bordered-primary">Medical Histories List</h3>
                    <h5>Add a patient new medical record <a href="{% url 'patient_tracking:medical-histories-create' %}" class="thm-btn">Add New Patient Medical Record</a></h5>
                    <div class="table-responsive">
                        <table class="table table-hover table-striped">
                            <caption></caption>
                            <thead>
                                <tr>
                                    <th scope="col" class="text-nowrap">SN.</th>
                                    <th scope="col" class="text-nowrap">Patient</th>
                                    <th scope="col" class="text-nowrap">Condition</thtion>
                                    <th scope="col" class="text-nowrap">Diagnosis Date</th>
                                    <th scope="col" class="text-nowrap">Description</th>
                                </tr>
                            </thead>
                            <tbody>
                                
                                {% for medical_history in object_list %}
                                    <tr>
                                        <td>{{ forloop.counter }}.</td>
                                        <td class="text-nowrap">{{medical_history.patient}}</td>
                                        <td class="text-nowrap">{{medical_history.condition}}</td>
                                        <td class="text-nowrap">{{medical_history.diagnosis_date}}</td>
                                        <td class="text-nowrap">{{medical_history.description}}</td>

                                        <td class="text-nowrap">
                                            <a href="{% url 'patient_tracking:medical-histories-edit' medical_history.id %}" class="btn btn-default">
                                                <i class="fa fa-pencil"></i> Edit
                                              </a>
                                            <a href="{% url 'patient_tracking:medical-histories-detail' medical_history.id %}" class="btn btn-primary">
                                              <i class="fa fa-eye"></i> View
                                            </a>
                                        </td>
                                    </tr>
                                    {% empty %}
                                    <h3>0 records</h3>
                                {%endfor%}
                            </tbody>
                        </table>
                    </div>                   
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

patient_tracking/templates/patient_tracking/medical_history/medical_history_list.html
{% extends 'website/base.html' %}
{% load static %}
{% block title %}
    Patient Tracking | Patients
{% endblock %}

{% block content %}

<section style="padding: 70px;" class="shadow">
    <div class="container">
        <div class="row my-row">
            <div class="col-12">
                <div class="about-des">
                    <h3 class="bordered bordered-2 border-bottom bordered-primary">Medical Histories List</h3>
                    <h5>Add a patient new medical record <a href="{% url 'patient_tracking:medical-histories-create' %}" class="thm-btn">Add New Patient Medical Record</a></h5>
                    <div class="table-responsive">
                        <table class="table table-hover table-striped">
                            <caption></caption>
                            <thead>
                                <tr>
                                    <th scope="col" class="text-nowrap">SN.</th>
                                    <th scope="col" class="text-nowrap">Patient</th>
                                    <th scope="col" class="text-nowrap">Condition</thtion>
                                    <th scope="col" class="text-nowrap">Diagnosis Date</th>
                                    <th scope="col" class="text-nowrap">Description</th>
                                </tr>
                            </thead>
                            <tbody>
                                
                                {% for medical_history in object_list %}
                                    <tr>
                                        <td>{{ forloop.counter }}.</td>
                                        <td class="text-nowrap">{{medical_history.patient}}</td>
                                        <td class="text-nowrap">{{medical_history.condition}}</td>
                                        <td class="text-nowrap">{{medical_history.diagnosis_date}}</td>
                                        <td class="text-nowrap">{{medical_history.description}}</td>

                                        <td class="text-nowrap">
                                            <a href="#" class="btn btn-default">
                                                <i class="fa fa-pencil"></i> Edit
                                              </a>
                                            <a href="#" class="btn btn-primary">
                                              <i class="fa fa-eye"></i> View
                                            </a>
                                        </td>
                                    </tr>
                                    {% empty %}
                                    <h3>0 records</h3>
                                {%endfor%}
                            </tbody>
                        </table>
                    </div>                   
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

patient_tracking/templates/patient_tracking/patients/patient_list.html
{% extends 'website/base.html' %}
{% load static %}
{% block title %}
    Patient Tracking | Patients
{% endblock %}

{% block content %}

<section style="padding: 70px;" class="shadow">
    <div class="container">
        <div class="row my-row">
            <div class="col-sm-6 col-md-2 hidden-xs hidden-sm">
                <img src="{% static 'website/images/about.jpg' %}" class="img-responsive" alt="">
            </div>
            <div class="col-sm-12 col-md-10">
                <div class="about-des">
                    <h3 class="bordered bordered-2 border-bottom bordered-primary">Registered Patients List</h3>
                    <h5>Register a patient to meet the doctor and keep track of medical records <a href="{% url 'patient_tracking:patients-create' %}" class="thm-btn">Register New Patient</a></h5>
                    <div class="table-responsive">
                        <table class="table table-hover table-striped">
                            <caption></caption>
                            <thead>
                                <tr>
                                    <th scope="col" class="text-nowrap">SN.</th>
                                    <th scope="col" class="text-nowrap">First Name</th>
                                    <th scope="col" class="text-nowrap">Last Name</th>
                                    <th scope="col" class="text-nowrap">Date of Birth</th>
                                    <th scope="col" class="text-nowrap">Gender</th>
                                    <th scope="col" class="text-nowrap">Phone Number</th>
                                    <th scope="col" class="text-nowrap">Email</th>
                                    <th scope="col" class="text-nowrap">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                
                                {% for patient in object_list %}
                                    <tr>
                                        <td>{{ forloop.counter }}.</td>
                                        <td class="text-nowrap">{{patient.first_name}}</td>
                                        <td class="text-nowrap">{{patient.last_name}}</td>
                                        <td class="text-nowrap">{{patient.date_of_birth}}</td>
                                        <td class="text-nowrap">{{patient.gender}}</td>
                                        <td class="text-nowrap">{{patient.phone_number}}</td>
                                        <td class="text-nowrap">{{patient.email}}</td>
                                        <td class="text-nowrap">
                                            <a href="{% url 'patient_tracking:patients-edit' patient.id %}" class="btn btn-default">
                                                <i class="fa fa-pencil"></i> Edit
                                              </a>
                                            <a href="{% url 'patient_tracking:patients-detail' patient.id %}" class="btn btn-primary">
                                              <i class="fa fa-eye"></i> View
                                            </a>
                                        </td>
                                    </tr>
                                    {% empty %}
                                    <h3>0 records</h3>
                                {%endfor%}
                            </tbody>
                        </table>
                    </div>                   
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}